### PR TITLE
Update devices.json

### PR DESCRIPTION
**Pull request by teejthehellian**
Add device Wikis for mondrianwifi, espressowifi.

### CODE REVIEW

**Comment by liammendes** [comment]
The devices.json file seems to contain more devices than is stated on download.lineageos.org, is there any API or another json file to only contain the devices on the LineageOS download website? I am making a app that downloads the latest LineageOS build for new users such as stock users etc and the last thing I want to do in my app is to download the hudson files, search the codenames in the devices.json and then return the results.....

**Comment by Stricted** [comment]
@liammendes see https://github.com/LineageOS/lineageos_updater/blob/master/app.py#L192

**Comment by liammendes** [comment]
@Stricted Thanks, I will commit it later to my repository at [https://www.github.com/liammendes/LineageOSDownloader](url)

**Comment by lineageos-gerrit** [comment]
Hi there;

This is an automated reply, to let you know LineageOS doesn't merge pull
requests submitted directly to our github.com repositories.

You can submit your change requests through our public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, we also suggest you take
a look at http://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Pull request closed without merging**
